comment: >-
    👍 Thanks for opening this issue!
    🏷 I have applied any labels matching special text in your issue.
labels:
    'bug':
        - '/\bbug[s]?\b/g'
    'help wanted':
        - '/\btest(ing)?\b/g'
    'Client: Csharp':
        - '/\bcsharp\b/g'
        - '/\b[Cc]#/g'
    'Server: Csharp':
        - '/\baspnetcore\b/g'

