comment: |
    👍 Thanks for opening this issue!
    🏷 I have applied any labels matching special text in your issue.

    Please review the labels and make any necessary changes.
labels:
    'bug':
        - '\bbug[s]?\b'
    'help wanted':
        - '\btest(ing)?\b'
    'Client: Csharp':
        - '\bcsharp\b'
        - '\b[Cc]#'
    'Server: Csharp':
        - '\baspnetcore\b'

